ARG RUBY_VERSION
FROM ruby:$RUBY_VERSION-alpine

# Configure environment variables
ENV LANG=C.UTF-8 \
  HOME=/app

# Make a $HOME
RUN mkdir $HOME
WORKDIR $HOME

# Install dependencies
RUN apk update \
  && apk add --no-cache \
    build-base \
    git \
    netcat-openbsd \
    nodejs \
    postgresql-dev \
    tzdata \
    yarn \
  && rm -rf /var/cache/apk/*

# Add a script to be executed every time the container starts.
COPY docker/rails/entrypoint-dev.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint-dev.sh

ENTRYPOINT ["entrypoint-dev.sh"]
